[build]
  base = "client"
  publish = "dist"
  command = "yarn install && yarn build"

[dev]
  command = "yarn dev"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200